[profile.default]
src = "src"
out = "out"
libs = ["lib"]

# Deterministic Deployments
bytecode_hash = 'none'
cbor_metadata = false

evm_version = 'cancun'
optimizer = true
optimizer_runs = 4_294_967_295
solc_version = '0.8.28'
via_ir = true
